# ***Compilacion Machine Learning*** ⚠️

some `Help` **in** *this ->* [Link](https://www.youtube.com/watch?v=7eh4d6sabA0)

# 1. NumPy - Exercise Complete Baseball

In this exercise, our goal is to harness the capabilities of Python, specifically leveraging key libraries such as `numpy` and `pandas`, to conduct a thorough analysis of a baseball dataset. Through the use of `pandas`, we read the dataset into a DataFrame, allowing us to explore and extract pertinent information such as player weights and heights. The subsequent conversion of these data points into NumPy arrays enables us to perform essential array operations, access individual elements, and create a 2D array for more in-depth analysis. As we delve into array properties, calculate basic statistics on height, including average and median, and explore the correlation between height and weight, this Jupyter Notebook serves as an interactive guide, providing a hands-on experience in utilizing Python for data manipulation and statistical insights, all within the fascinating context of baseball analytics.

In [11]:
# Import necessary libraries
import pandas as pd
import numpy as np

# Step 1: Read the MLB (Baseball) dataset into a pandas DataFrame
mlb = pd.read_csv("MLB (Baseball).txt")
print(mlb.head(3))  # Print the first 3 rows of the DataFrame

# Step 2: Extract weight and height columns from the DataFrame
weight_lb = mlb['Weight'].tolist()
height_in = mlb['Height'].tolist()

# Step 3: Store weight and height lists as numpy arrays
np_weight_lb = np.array(weight_lb)
np_height_in = np.array(height_in)

# accesing to the 'height' column (column index 0)
height_column = np_baseball[:, 0]

# Step 4: Access individual elements and columns in the arrays
print("Weight at index 50:", np_weight_lb[49])  # Indexing starts from 0
print("Height from index 100 to 110:", np_height_in[99:110]) #show from...to...
print("Height column:", height_column) #show 'height' column

# Step 5: Create np_baseball from the DataFrame
np_baseball = mlb[['Height', 'Weight']].to_numpy()

# Step 6: Explore the properties of np_baseball
print("Type of np_baseball:", type(np_baseball))
print("Shape of np_baseball:", np_baseball.shape)
print("50th row of np_baseball:", np_baseball[49, :])
print("Height of 124th player:", np_baseball[123, 0])

# Step 7: Calculate statistics for height, same way to do for "weight"
avg_height = np.mean(np_baseball[:, 0])
med_height = np.median(np_baseball[:, 0])
stddev_height = np.std(np_baseball[:, 0])
corr_height_weight = np.corrcoef(np_baseball[:, 0], np_baseball[:, 1])

# Step 8: Print height statistics, same way to do for "weight"
print("Average Height:", avg_height)
print("Median Height:", med_height)
print("Standard Deviation of Height:", stddev_height)
print("Correlation between Height and Weight:", corr_height_weight[0, 1])

# Step 9: Print additional statistics for height, same way to do for "weight"
print("Mean of Height:", np.mean(np_height_in))
print("Median of Height:", np.median(np_height_in))

# steps 7,8 & 9 can works also to show statistics about 'weight'

              Name Team Position  Height  Weight    Age PosCategory
0    Adam_Donachie  BAL  Catcher      74     180  22.99     Catcher
1        Paul_Bako  BAL  Catcher      74     215  34.69     Catcher
2  Ramon_Hernandez  BAL  Catcher      72     210  30.78     Catcher
Weight at index 50: 195
Height from index 100 to 110: [74 73 74 72 73 69 72 73 75 75 73]
Height column: [74 74 72 ... 75 75 73]
Type of np_baseball: <class 'numpy.ndarray'>
Shape of np_baseball: (1015, 2)
50th row of np_baseball: [ 70 195]
Height of 124th player: 75
Average Height: 73.6896551724138
Median Height: 74.0
Standard Deviation of Height: 2.312791881046546
Correlation between Height and Weight: 0.5315393226146095
Mean of Height: 73.6896551724138
Median of Height: 74.0

# 2.1. for looping common operations

In [2]:
# Loop through a list of numbers
numbers = [1, 2, 3, 4, 5]
print("Loop through a list of numbers:")
for number in numbers:
    print(number)

# Loop through a range of numbers
print("\nLoop through a range of numbers:")
for i in range(5):
    print(i)

# Loop through characters in a string
print("\nLoop through characters in a string:")
for char in "Python":
    print(char)

# Loop through key-value pairs in a dictionary
print("\nLoop through key-value pairs in a dictionary:")
person = {'name': 'John', 'age': 30, 'city': 'New York'}
for key, value in person.items():
    print(key, value)

# Loop through elements with index using enumerate
print("\nLoop through elements with index using enumerate:")
fruits = ['apple', 'banana', 'cherry']
for index, fruit in enumerate(fruits):
    print(index, fruit)

# Nested loops
print("\nNested loops:")
for i in range(3):
    for j in range(3):
        print(i, j)

# Continue statement to skip iteration
print("\nContinue statement to skip iteration:")
numbers = [1, 2, 3, 4, 5]
for number in numbers:
    if number == 3:
        continue  # Skip the rest of the loop for this iteration
    print(number)

# Loop with else statement
print("\nLoop with else statement:")
for i in range(5):
    print(i)
else:
    print("Loop completed without a break.")

Loop through a list of numbers:
1
2
3
4
5

Loop through a range of numbers:
0
1
2
3
4

Loop through characters in a string:
P
y
t
h
o
n

Loop through key-value pairs in a dictionary:
name John
age 30
city New York

Loop through elements with index using enumerate:
0 apple
1 banana
2 cherry

Nested loops:
0 0
0 1
0 2
1 0
1 1
1 2
2 0
2 1
2 2

Continue statement to skip iteration:
1
2
4
5

Loop with else statement:
0
1
2
3
4
Loop completed without a break.

# 2.2. if - else statements

In [14]:
# Example: Check conditions and perform actions accordingly

# Scenario 1: Numeric Comparison
x = 10
if x > 5:
    print("x is greater than 5")
elif x == 5:
    print("x is equal to 5")
else:
    print("x is less than 5")

# Scenario 2: String Comparison
country = "USA"
if country == "USA":
    print("Country is United States")
elif country == "Canada":
    print("Country is Canada")
else:
    print("Country is neither USA nor Canada")

# Scenario 3: Checking for Membership
fruits = ['apple', 'banana', 'orange']
fruit_to_check = 'banana'
if fruit_to_check in fruits:
    print(f"{fruit_to_check} is in the list")
else:
    print(f"{fruit_to_check} is not in the list")

# Scenario 4: Logical Conditions
age = 25
income = 50000
if age > 18 and income > 30000:
    print("Eligible for loan")
else:
    print("Not eligible for loan")

# Scenario 5: Nested if-else
temperature = 28
if temperature > 30:
    print("High temperature detected")
else:
    print("Normal or low temperature detected")
    if temperature < 0:
        print("Extreme cold temperature detected")

# Scenario 6: Ternary Operator
x = 10
message = "Even" if x % 2 == 0 else "Odd"
print(message)

# Scenario 7: Checking for None
value = None
if value is None:
    print("Value is None")
else:
    print("Value is not None")

# Scenario 8: Using not in conditions
is_raining = False
if not is_raining:
    print("No need for an umbrella")
else:
    print("Bring an umbrella")

# Scenario 9: Multiple conditions using or
day = "Saturday"
if day == "Saturday" or day == "Sunday":
    print("It's the weekend!")
else:
    print("It's a weekday")

# Scenario 10: Multiple conditions using and
temperature = 25
if temperature > 20 and temperature < 30:
    print("Temperature is comfortable")
else:
    print("Temperature is not in the comfort range")

x is greater than 5
Country is United States
banana is in the list
Eligible for loan
Normal or low temperature detected
Even
Value is None
No need for an umbrella
It's the weekend!
Temperature is comfortable

# 2.3. While loop over conditions

In [15]:
# Simple While Loop:
print("Simple While Loop:")
count = 0
while count < 5:
    print(count)
    count += 1

# Using else with While Loop:
print("\nUsing else with While Loop:")
count = 0
while count < 5:
    print(count)
    count += 1
else:
    print("Loop completed without a break.")

# While Loop with continue:
print("\nWhile Loop with continue:")
count = 0
while count < 5:
    count += 1
    if count == 3:
        continue  # Skip the rest of the loop for this iteration
    print(count)

# Using break to Exit Loop Prematurely:
print("\nUsing break to Exit Loop Prematurely:")
count = 0
while count < 5:
    if count == 3:
        break  # Exit the loop when count is 3
    print(count)
    count += 1

# While Loop with Condition:
print("\nWhile Loop with Condition:")
temperature = 3
while temperature < 10:
    print(f"Temperature is {temperature}°C. Heating...")
    temperature += 1

# Using else with a Condition:
print("\nUsing else with a Condition:")
temperature = 0
while temperature < 100:
    print(f"Temperature is {temperature}°C. Heating...")
    temperature += 10
else:
    print("Reached maximum temperature.")

Simple While Loop:
0
1
2
3
4

Using else with While Loop:
0
1
2
3
4
Loop completed without a break.

While Loop with continue:
1
2
4
5

Using break to Exit Loop Prematurely:
0
1
2

While Loop with Condition:
Temperature is 3°C. Heating...
Temperature is 4°C. Heating...
Temperature is 5°C. Heating...
Temperature is 6°C. Heating...
Temperature is 7°C. Heating...
Temperature is 8°C. Heating...
Temperature is 9°C. Heating...

Using else with a Condition:
Temperature is 0°C. Heating...
Temperature is 10°C. Heating...
Temperature is 20°C. Heating...
Temperature is 30°C. Heating...
Temperature is 40°C. Heating...
Temperature is 50°C. Heating...
Temperature is 60°C. Heating...
Temperature is 70°C. Heating...
Temperature is 80°C. Heating...
Temperature is 90°C. Heating...
Reached maximum temperature.

# 2.4. Complete Cars

The overall purpose is to showcase common operations when working with Pandas DataFrames, including data retrieval, column selection, slicing, and label-based indexing. It's a practical example for understanding and manipulating tabular data using Pandas.

## **working from array dataframe**

In [57]:
# Import the necessary libraries
import pandas as pd

# creting the Array DataFrame
data = {
    'cars_per_cap': [809, 731, 588, 18, 200, 70, 45],
    'country': ['United States', 'Australia', 'Japan', 'India', 'Russia', 'Morocco', 'Egypt'],
    'drives_right': [True, False, False, False, True, True, True]
}

cars = pd.DataFrame(data)
# Display the original DataFrame
print("Original DataFrame:")
print(cars)

# Drop rows with NaN values, if any
cars_cleaned = cars.dropna()
# Display the DataFrame after dropping rows with NaN (in this case, there shouldn't be any)
print("\nDataFrame after dropping rows with NaN:")
print(cars_cleaned)

# Drop duplicate rows, if any
cars_cleaned = cars_cleaned.drop_duplicates()
# Display the DataFrame after dropping duplicate rows (in this case, there shouldn't be any)
print("\nDataFrame after dropping duplicate rows:")
print(cars_cleaned)

# Drop rows with duplicate values in the 'country' column
cars_cleaned = cars_cleaned.drop_duplicates(subset='country')
# Display the DataFrame after dropping rows with duplicate values based on 'country'
print("\nDataFrame after dropping rows with duplicate values in 'country':")
print(cars_cleaned)

# Reset the index of the DataFrame after cleaning operations
cars_cleaned.reset_index(drop=True, inplace=True)
# Display the DataFrame with the reset index
print("\nDataFrame with the reset index:")
print(cars_cleaned)

# Print the first 3 observations in the DataFrame
print("\nFirst 3 observations in the DataFrame:")
print(cars_cleaned.head(3))
# Print observations 4, 5, and 6 in the DataFrame
print("\nObservations 4, 5, and 6 in the DataFrame:")
print(cars_cleaned[3:6])

# Print the observation for Japan using label-based indexing (loc)
print("\nObservation for Japan using loc:")
print(cars_cleaned.loc[cars_cleaned['country'] == 'Japan'])

# Print observations for Australia and Egypt using label-based indexing
print("\nObservations for Australia and Egypt using loc:")
print(cars_cleaned.loc[cars_cleaned['country'].isin(['Australia', 'Egypt'])])

# Print the 'drives_right' value for Morocco using label-based indexing
print("\n'Drives_right' value for Morocco using loc:")
print(cars_cleaned.loc[cars_cleaned['country'] == 'Morocco', 'drives_right'])

# Print a sub-DataFrame for Russia and Morocco with selected columns
print("\nSub-DataFrame for Russia and Morocco with selected columns:")
print(cars_cleaned.loc[cars_cleaned['country'].isin(['Russia', 'Morocco']), ['country', 'drives_right']])

# Print the 'drives_right' column as a Pandas Series
print("\n'Drives_right' column as a Pandas Series:")
print(cars_cleaned['drives_right'])

# Print the 'drives_right' column as a Pandas DataFrame
print("\n'Drives_right' column as a Pandas DataFrame:")
print(cars_cleaned[['drives_right']])

# Print 'cars_per_cap' and 'drives_right' columns as a DataFrame
print("\n'cars_per_cap' and 'drives_right' columns as a DataFrame:")
print(cars_cleaned[['cars_per_cap', 'drives_right']])

Original DataFrame:
   cars_per_cap        country  drives_right
0           809  United States          True
1           731      Australia         False
2           588          Japan         False
3            18          India         False
4           200         Russia          True
5            70        Morocco          True
6            45          Egypt          True

DataFrame after dropping rows with NaN:
   cars_per_cap        country  drives_right
0           809  United States          True
1           731      Australia         False
2           588          Japan         False
3            18          India         False
4           200         Russia          True
5            70        Morocco          True
6            45          Egypt          True

DataFrame after dropping duplicate rows:
   cars_per_cap        country  drives_right
0           809  United States          True
1           731      Australia         False
2           588          Japan         False
3            18          India         False
4           200         Russia          True
5            70        Morocco          True
6            45          Egypt          True

DataFrame after dropping rows with duplicate values in 'country':
   cars_per_cap        country  drives_right
0           809  United States          True
1           731      Australia         False
2           588          Japan         False
3            18          India         False
4           200         Russia          True
5            70        Morocco          True
6            45          Egypt          True

DataFrame with the reset index:
   cars_per_cap        country  drives_right
0           809  United States          True
1           731      Australia         False
2           588          Japan         False
3            18          India         False
4           200         Russia          True
5            70        Morocco          True
6            45          Egypt          True

First 3 observations in the DataFrame:
   cars_per_cap        country  drives_right
0           809  United States          True
1           731      Australia         False
2           588          Japan         False

Observations 4, 5, and 6 in the DataFrame:
   cars_per_cap  country  drives_right
3            18    India         False
4           200   Russia          True
5            70  Morocco          True

Observation for Japan using loc:
   cars_per_cap country  drives_right
2           588   Japan         False

Observations for Australia and Egypt using loc:
   cars_per_cap    country  drives_right
1           731  Australia         False
6            45      Egypt          True

'Drives_right' value for Morocco using loc:
5    True
Name: drives_right, dtype: bool

Sub-DataFrame for Russia and Morocco with selected columns:
   country  drives_right
4   Russia          True
5  Morocco          True

'Drives_right' column as a Pandas Series:
0     True
1    False
2    False
3    False
4     True
5     True
6     True
Name: drives_right, dtype: bool

'Drives_right' column as a Pandas DataFrame:
   drives_right
0          True
1         False
2         False
3         False
4          True
5          True
6          True

'cars_per_cap' and 'drives_right' columns as a DataFrame:
   cars_per_cap  drives_right
0           809          True
1           731         False
2           588         False
3            18         False
4           200          True
5            70          True
6            45          True

## **working from CSV file**

In [58]:
# Import the necessary libraries
import pandas as pd

# Load the DataFrame from the CSV file
cars = pd.read_csv('cars.csv', index_col=0)

# Display the original DataFrame
print("Original DataFrame:")
print(cars)

# Drop rows with NaN values, if any
cars_cleaned = cars.dropna()

# Display the DataFrame after dropping rows with NaN (in this case, there shouldn't be any)
print("\nDataFrame after dropping rows with NaN:")
print(cars_cleaned)

# Drop duplicate rows, if any
cars_cleaned = cars_cleaned.drop_duplicates()

# Display the DataFrame after dropping duplicate rows (in this case, there shouldn't be any)
print("\nDataFrame after dropping duplicate rows:")
print(cars_cleaned)

# Drop rows with duplicate values in the 'country' column
cars_cleaned = cars_cleaned.drop_duplicates(subset='country')

# Display the DataFrame after dropping rows with duplicate values based on 'country'
print("\nDataFrame after dropping rows with duplicate values in 'country':")
print(cars_cleaned)

# Reset the index of the DataFrame after cleaning operations
cars_cleaned.reset_index(drop=True, inplace=True)

# Display the DataFrame with the reset index
print("\nDataFrame with the reset index:")
print(cars_cleaned)

# Print the first 3 observations in the DataFrame
print("\nFirst 3 observations in the DataFrame:")
print(cars_cleaned.head(3))

# Print observations 4, 5, and 6 in the DataFrame
print("\nObservations 4, 5, and 6 in the DataFrame:")
print(cars_cleaned[3:6])

# Print the observation for Japan using label-based indexing (loc)
print("\nObservation for Japan using loc:")
print(cars_cleaned.loc[cars_cleaned['country'] == 'Japan'])

# Print observations for Australia and Egypt using label-based indexing
print("\nObservations for Australia and Egypt using loc:")
print(cars_cleaned.loc[cars_cleaned['country'].isin(['Australia', 'Egypt'])])

# Print the 'drives_right' value for Morocco using label-based indexing
print("\n'Drives_right' value for Morocco using loc:")
print(cars_cleaned.loc[cars_cleaned['country'] == 'Morocco', 'drives_right'])

# Print a sub-DataFrame for Russia and Morocco with selected columns
print("\nSub-DataFrame for Russia and Morocco with selected columns:")
print(cars_cleaned.loc[cars_cleaned['country'].isin(['Russia', 'Morocco']), ['country', 'drives_right']])

# Print the 'drives_right' column as a Pandas Series
print("\n'Drives_right' column as a Pandas Series:")
print(cars_cleaned['drives_right'])

# Print the 'drives_right' column as a Pandas DataFrame
print("\n'Drives_right' column as a Pandas DataFrame:")
print(cars_cleaned[['drives_right']])

# Print 'cars_per_cap' and 'drives_right' columns as a DataFrame
print("\n'cars_per_cap' and 'drives_right' columns as a DataFrame:")
print(cars_cleaned[['cars_per_cap', 'drives_right']])

Original DataFrame:
    Unnamed: 0  cars_per_cap        country  drives_right
NaN         US           809  United States          True
NaN        AUS           731      Australia         False
NaN        JAP           588          Japan         False
NaN         IN            18          India         False
NaN         RU           200         Russia          True
NaN        MOR            70        Morocco          True
NaN         EG            45          Egypt          True

DataFrame after dropping rows with NaN:
    Unnamed: 0  cars_per_cap        country  drives_right
NaN         US           809  United States          True
NaN        AUS           731      Australia         False
NaN        JAP           588          Japan         False
NaN         IN            18          India         False
NaN         RU           200         Russia          True
NaN        MOR            70        Morocco          True
NaN         EG            45          Egypt          True

DataFrame after dropping duplicate rows:
    Unnamed: 0  cars_per_cap        country  drives_right
NaN         US           809  United States          True
NaN        AUS           731      Australia         False
NaN        JAP           588          Japan         False
NaN         IN            18          India         False
NaN         RU           200         Russia          True
NaN        MOR            70        Morocco          True
NaN         EG            45          Egypt          True

DataFrame after dropping rows with duplicate values in 'country':
    Unnamed: 0  cars_per_cap        country  drives_right
NaN         US           809  United States          True
NaN        AUS           731      Australia         False
NaN        JAP           588          Japan         False
NaN         IN            18          India         False
NaN         RU           200         Russia          True
NaN        MOR            70        Morocco          True
NaN         EG            45          Egypt          True

DataFrame with the reset index:
  Unnamed: 0  cars_per_cap        country  drives_right
0         US           809  United States          True
1        AUS           731      Australia         False
2        JAP           588          Japan         False
3         IN            18          India         False
4         RU           200         Russia          True
5        MOR            70        Morocco          True
6         EG            45          Egypt          True

First 3 observations in the DataFrame:
  Unnamed: 0  cars_per_cap        country  drives_right
0         US           809  United States          True
1        AUS           731      Australia         False
2        JAP           588          Japan         False

Observations 4, 5, and 6 in the DataFrame:
  Unnamed: 0  cars_per_cap  country  drives_right
3         IN            18    India         False
4         RU           200   Russia          True
5        MOR            70  Morocco          True

Observation for Japan using loc:
  Unnamed: 0  cars_per_cap country  drives_right
2        JAP           588   Japan         False

Observations for Australia and Egypt using loc:
  Unnamed: 0  cars_per_cap    country  drives_right
1        AUS           731  Australia         False
6         EG            45      Egypt          True

'Drives_right' value for Morocco using loc:
5    True
Name: drives_right, dtype: bool

Sub-DataFrame for Russia and Morocco with selected columns:
   country  drives_right
4   Russia          True
5  Morocco          True

'Drives_right' column as a Pandas Series:
0     True
1    False
2    False
3    False
4     True
5     True
6     True
Name: drives_right, dtype: bool

'Drives_right' column as a Pandas DataFrame:
   drives_right
0          True
1         False
2         False
3         False
4          True
5          True
6          True

'cars_per_cap' and 'drives_right' columns as a DataFrame:
   cars_per_cap  drives_right
0           809          True
1           731         False
2           588         False
3            18         False
4           200          True
5            70          True
6            45          True

# working with functions

In [6]:

import pandas as pd

# Create a DataFrame
df = pd.DataFrame({'lang': ['Python', 'Java', 'Python', 'C++', 'Python']})


# Define count_entries()
def count_entries(df, col_name='lang'):
    """Return a dictionary with counts of
    occurrences as value for each key."""
    
    # Raise a ValueError if col_name is NOT in DataFrame
    if col_name not in df.columns:
        raise ValueError('The DataFrame does not have a '+col_name+' column.')

    # Initialize an empty dictionary: cols_count
    cols_count = {}
    
    # Extract column from DataFrame: col
    col = df[col_name]
    
    # Iterate over the column in DataFrame
    for entry in col:

        # If entry is in cols_count, add 1
        if entry in cols_count.keys():
            cols_count[entry] += 1
            # Else add the entry to cols_count, set the value to 1
        else:
            cols_count[entry] = 1
        
        # Return the cols_count dictionary
    return cols_count

# Call count_entries(): result1
result1 = count_entries(df)

# Print result1
print(result1)

{'Python': 3, 'Java': 1, 'C++': 1}